disable_all_formatting = false

indent_style = "Block"
use_small_heuristics = "Max"
binop_separator = "Front"
combine_control_expr = true
comment_width = 80
condense_wildcard_suffixes = true
control_brace_style = "AlwaysSameLine"
error_on_line_overflow = false
error_on_unformatted = false
fn_args_layout = "Tall"
brace_style = "SameLineWhere"
empty_item_single_line = true
fn_single_line = false
where_single_line = false
force_explicit_abi = true
format_strings = true
format_macro_matchers = true
format_macro_bodies = true
hard_tabs = false
imports_indent = "Block"
imports_layout = "HorizontalVertical"
merge_imports = true
match_block_trailing_comma = true
max_width = 80
merge_derives = true
force_multiline_blocks = false
newline_style = "Unix"
normalize_comments = false
remove_nested_parens = true
reorder_imports = true
reorder_modules = false
reorder_impl_items = false
report_todo = "Never"
report_fixme = "Never"
skip_children = false
space_after_colon = true
space_before_colon = false
struct_field_align_threshold = 0
spaces_around_ranges = true
struct_lit_single_line = true
tab_spaces = 4
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
match_arm_blocks = true
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0
hide_parse_errors = false
unstable_features = true

